config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # get 'order_items/create'
  # get 'order_items/update'
  # get 'order_items/destroy'
  # get 'carts/show'
  # get 'product_orders/index'
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  scope "(:locale)", locale: /en|vi/ do
    root "pages#home"
    get "/about", to: "pages#about"
    get "/revervation", to: "pages#revervation"
    get "/gallery", to: "pages#gallery"
    get "index", to: "blogs#index"
    resources :blogs, only: [:index, :show]
    resource :cart, only: :show
    resources :order_items, only: [:create, :update, :destroy]

    resources :products do 
      resources :reviews
    end
  end
  namespace :admin do
    root "categories#index"
    get "dashboard/index"
    resources :categories
    resources :products
    resources :users
  end

  devise_for :users, path: '', path_names: { sign_in: 'login',
    sign_out: 'logout', edit: "profile", confirmation: "confirmation", },
    controllers: { omniauth_callbacks: "omniauth_callbacks"}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :users
  belongs_to :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  before_create :set_order_status

  before_save :update_subtotal

  has_many :order_items

  enum status: {"đang đặt hàng": 0, "đã đặt hàng": 1, "đã giao hàng": 2, "huỷ đơn": 3}

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private
  def set_order_status
    self.status = "đang đặt hàng"
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true,
    numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    persisted? ? self[:unit_price] : product.price
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active")
    end
  end

  def order_present
    if order.nil?
      errors.add(:oder, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user 

  has_many :order_items
  has_many :rates
  has_many :comments
  has_many :reviews
  
  mount_uploader :picture, PictureUploader
  
  validates :price, numericality: { greater_than_or_equal_to: 0,
                                    only_integer: true }
  validates :category_id, presence: true
  validate :picture_size
  
  def self.get_random_products_for_home_page
    self.order("RANDOM()").limit(12)
  end
  
  private
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "Should be less than 5MB")
    end
  end
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :users
  belongs_to :products
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/suggest_item.rb
class SuggestItem < ApplicationRecord
  belongs_to :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, 
    :validatable,:trackable, :lockable, :timeoutable, :omniauthable
  has_many :orders
  has_many :rates
  has_many :comments
  has_many :suggest_items
  has_many :reviews

  def role
    role = self.admin? ? "Admin" : "Normal User"
  end

  def self.find_for_google_oauth2(provider, uid, name, email, signed_in_resource = nil)
    user = User.where(:provider => provider, :uid => uid).first
    if user
      user.skip_confirmation!
      user.skip_confirmation_notification!
      user.save
      return user
    else
      registered_user = User.where(:email => email).first
      if registered_user
        registered_user.skip_confirmation!
        registered_user.skip_confirmation_notification!
        registered_user.save
        return registered_user
      else
        user = User.new(
          name: name,
          provider: provider,
          email: email,
          uid: uid,
          password: Devise.friendly_token[0, 20]
        )
        user.skip_confirmation!
        user.skip_confirmation_notification!
        user.save
        return user
      end
    end
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = "123456"
      user.name = auth.info.name  
    end
  end
 
  def self.find_for_facebook_oauth(provider, uid, name, email, signed_in_resource = nil)
    user = User.where(:provider => provider, :uid => uid).first

    if user
      user.skip_confirmation!
      user.skip_confirmation_notification!
      user.save
      return user
    else
      registered_user = User.where(:email => email).first
      if registered_user
        # registered_user.skip_confirmation!
        # registered_user.skip_confirmation_notification!
        registered_user.save
        return registered_user
      else
        user = User.new(
          name: name,
          provider: provider,
          email: email,
          uid: uid,
          password: Devise.friendly_token[0, 20]
        )
        user.skip_confirmation!
        user.skip_confirmation_notification!
        user.save
        return user
      end
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index; end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def show
    @product = Product.find_by id: params[:id]
    if @product.reviews.blank? 
      @average_review = 0
    else
      @average_review  = @product.reviews.average(:rating).round(2)
    end
   
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
  def home
    @products = Product.get_random_products_for_home_page
    @categories = Category.all
    @order_item = current_order.order_items.new
  end

  def gallery
    @products = Product.all
  end

  def about; end

  def revervation; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  
  def new
    @user = User.new
  end

  def index; end

  def show
    @user = User.find_by id: params[:id]
    redirect_to root_path unless @user
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Please check your email to activate your account"
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @user = User.find_by id: params[:id]
    redirect_to root_path unless @user
  end

  def update
    @user = User.find_by id: params[:id]
    if @user.update user_params
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :password, :email, :address, :phone
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basics
  def full_title page_title = ""
    base_title = "Restaurant"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/product_orders_helper.rb
module ProductOrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/dashboard/_header_dashboard.html.erb
<header class="navbar navbar-expand-lg navbar-light"
  style="background-color: #837a65;">
  <div class="container">
    <%= link_to image_tag("logo.png", class: "navbar-brand"), root_path %>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <!-- Language -->
        <div class="dropdown">
          <button class="btn btn-outline-dark dropdown-toggle" type="button"
            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false"><%= t(".Languages") %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li>
              <%= link_to t(".English"), locale:"en", class: "dropdown-item"%>
            </li>
            <li>
              <%= link_to t(".Vietnamese"), locale:"vi",  
                class: "dropdown-item" %> 
            </li>
          </div>
        </div>
        <!-- End language -->

        <li class="nav-item mr-1">
          <%= link_to t(".home"), root_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-1">
          <%= link_to t(".users"), admin_users_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-1">
          <%= link_to t(".products"), admin_products_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-1">
          <%= link_to t(".categories"), admin_categories_path, 
            class: "nav-link" %>
        </li>

        <% if !user_signed_in? %>
          <li class="nav-item mr-1">
            <%= link_to t(".sign_up"), new_user_registration_path, 
              class: "nav-link btn btn-warning fa fa-user-plus" %>
          </li>
          <li class="nav-item mr-1">
            <%= link_to t(".log_in"), new_user_session_path, 
              class: "nav-link btn btn-success fa fa-lock" %>
          </li>
        <% else %>
        <li>
          <% if current_user.admin? %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" 
                id="dropdownMenuButton" data-toggle="dropdown" 
                aria-haspopup="true" aria-expanded="false">

                <%= current_user.name %>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to t(".change_password"),edit_user_registration_path, 
                  class: "dropdown-item" %>
                <%= link_to t(".log_out"),destroy_user_session_path, 
                  method: :delete, class: "dropdown-item" %>
              </div>
            </div>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/admin/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-3">
      <h1>Welcome to the admin page</h1>
      </div>
    </div>
  </div>
</div>