config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # get 'order_items/create'
  # get 'order_items/update'
  # get 'order_items/destroy'
  # get 'carts/show'
  # get 'product_orders/index'
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  scope "(:locale)", locale: /en|vi/ do
    root "pages#home"
    get "/about", to: "pages#about"
    get "/revervation", to: "pages#revervation"
    get "/gallery", to: "pages#gallery"
    get "index", to: "blogs#index"
    resources :blogs, only: [:index, :show]
    resource :cart, only: :show
    resources :order_items, only: [:create, :update, :destroy]

    resources :products do 
      resources :reviews
    end
  end
  namespace :admin do
    root "categories#index"
    get "dashboard/index"
    resources :categories
    resources :products
    resources :users
  end

  devise_for :users, path: '', path_names: { sign_in: 'login',
    sign_out: 'logout', edit: "profile", confirmation: "confirmation", },
    controllers: { omniauth_callbacks: "omniauth_callbacks"}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by id: params[:id]
    redirect_to root_path unless @category
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save 
      flash[:success] = t(".create_category")
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find_by id: params[:id]
    redirect_to root_path unless @category
  end

  def update
    @category = Category.find_by id: params[:id]
    if @category.update_attributes category_params
      flash[:success] = t(".update_category")
      redirect_to admin_categories_path
    else
      render :edit
    end
  end
  
  def destroy
    @category = Category.find_by id: params[:id]
    @category.destroy
    redirect_to admin_categories_path
  end
  
  private
  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by :id params[:id]
    redirect_to root_path unless @category
  end
end

app/views/admin/categories/edit.html.erb
<% provide :title, t(".edit_category") %>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for [:admin, @category] do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="field mt-2">
        <%= f.submit t(".update"), class: "btn btn-primary form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t(".all_categores") %>
<%= link_to t(".create_new_category"), new_admin_category_path,
  class: "btn btn-primary mb-1" %>
<table class="table table-bordered width_tabl">
  <tr class="background_tr">
    <th><%= t(".name") %></th>
    <th><%= t(".show_all_products") %></th>
    <th><%= t(".edit") %></th>
    <th><%= t(".delete") %></th>
  </tr>
  <% @categories.each do |category| %> 
    <tr>
      <th><%= category.name %></th>
      <th><%= link_to t(".show_all_products"), admin_category_path(category.id) %></th>
      <th><%= link_to t(".edit"), edit_admin_category_path(category.id) %></th>
       <td><%= link_to t(".delete"), admin_category_path(category.id),
        method: :delete,
        data: { confirm: t(".are_you_sure") } %></td>
    </tr>
  <% end %> 
</table>

app/views/admin/categories/new.html.erb
<% provide :title, t(".create_category") %>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for [:admin, @category] do |f| %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="actions mt-2">
        <%= f.submit t(".create_category"), class: "btn btn-primary form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <table class="table table-bordered ewidth_tabl">
        <tr class="background_tr">
          <th><%= t(".image") %></th>
          <th><%= t(".name") %></th>
          <th><%= t(".price") %></th>
          <th><%= t(".description") %></th>
          <th><%= t(".status") %></th>
          <th><%= t(".show") %></th>
          <th><%= t(".edit") %></th>
          <th><%= t(".delete") %></th>
        </tr>
        
        <% @category.products.each do |product| %>
        <tr>
          <% picture_url =  product&.picture&.url %>
          <% picture_url =
            picture_url.present? ? picture_url : "default_image_product.jpg" %>
          <th><%= image_tag picture_url ,
            class: "img-responsive", size: "50x50" %></th>
          <th><%= product.name %></th>
          <th><%= product.price %></th>
          <th><%= product.description %></th>
          <th><%= product.status %></th>
          <td><%= link_to t(".show"), admin_product_path(product.id) %></td>
          <td><%= link_to t(".edit"), edit_admin_product_path(product.id) %></td>
          <td><%= link_to t(".delete"), admin_product_path(product.id),
            method: :delete,
            data: { confirm: t(".are_you_sure") } %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>