config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # get 'order_items/create'
  # get 'order_items/update'
  # get 'order_items/destroy'
  # get 'carts/show'
  # get 'product_orders/index'
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  scope "(:locale)", locale: /en|vi/ do
    root "pages#home"
    get "/about", to: "pages#about"
    get "/revervation", to: "pages#revervation"
    get "/gallery", to: "pages#gallery"
    get "index", to: "blogs#index"
    resources :blogs, only: [:index, :show]
    resource :cart, only: :show
    resources :order_items, only: [:create, :update, :destroy]

    resources :products do 
      resources :reviews
    end
  end
  namespace :admin do
    root "categories#index"
    get "dashboard/index"
    resources :categories
    resources :products
    resources :users
  end

  devise_for :users, path: '', path_names: { sign_in: 'login',
    sign_out: 'logout', edit: "profile", confirmation: "confirmation", },
    controllers: { omniauth_callbacks: "omniauth_callbacks"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, 
    :validatable,:trackable, :lockable, :timeoutable, :omniauthable
  has_many :orders
  has_many :rates
  has_many :comments
  has_many :suggest_items
  has_many :reviews

  def role
    role = self.admin? ? "Admin" : "Normal User"
  end

  def self.find_for_google_oauth2(provider, uid, name, email, signed_in_resource = nil)
    user = User.where(:provider => provider, :uid => uid).first
    if user
      user.skip_confirmation!
      user.skip_confirmation_notification!
      user.save
      return user
    else
      registered_user = User.where(:email => email).first
      if registered_user
        registered_user.skip_confirmation!
        registered_user.skip_confirmation_notification!
        registered_user.save
        return registered_user
      else
        user = User.new(
          name: name,
          provider: provider,
          email: email,
          uid: uid,
          password: Devise.friendly_token[0, 20]
        )
        user.skip_confirmation!
        user.skip_confirmation_notification!
        user.save
        return user
      end
    end
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = "123456"
      user.name = auth.info.name  
    end
  end
 
  def self.find_for_facebook_oauth(provider, uid, name, email, signed_in_resource = nil)
    user = User.where(:provider => provider, :uid => uid).first

    if user
      user.skip_confirmation!
      user.skip_confirmation_notification!
      user.save
      return user
    else
      registered_user = User.where(:email => email).first
      if registered_user
        # registered_user.skip_confirmation!
        # registered_user.skip_confirmation_notification!
        registered_user.save
        return registered_user
      else
        user = User.new(
          name: name,
          provider: provider,
          email: email,
          uid: uid,
          password: Devise.friendly_token[0, 20]
        )
        user.skip_confirmation!
        user.skip_confirmation_notification!
        user.save
        return user
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :find_user, only: [:edit, :show]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save 
      flash[:success]  = t(".create_user")
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    @user = User.find_by id: params[:id]
    if @user.update_attributes user_params
      flash[:success] = t(".update_user")
      redirect_to admin_users_path
    else
      render :edit
    end
  end
  def destroy
    @user = User.find_by id: params[:id] 
    @user.destroy
    redirect_to admin_users_path
  end

  private 
  def user_params
    params.require(:user).permit :name, :email, :address, :phone, :password, :role
  end

  def find_user
    @user = User.find_by id: params[:id]
    redirect_to root_path unless @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  
  def new
    @user = User.new
  end

  def index; end

  def show
    @user = User.find_by id: params[:id]
    redirect_to root_path unless @user
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Please check your email to activate your account"
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @user = User.find_by id: params[:id]
    redirect_to root_path unless @user
  end

  def update
    @user = User.find_by id: params[:id]
    if @user.update user_params
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :password, :email, :address, :phone
  end
end

app/views/admin/users/edit.html.erb
<h1 class="text-center"><%= t(".edit_user") %></h1>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for [:admin, @user] do |f| %> 
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_field :address, class: "form-control" %>
      </div>
      
      <div class="field">
        <%= f.label :phone %><br />
        <%= f.text_field :phone, class: "form-control" %>
      </div>
      
      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, class: "form-control" %>
      </div> 

      <div class="field mt-3 border">
        <%= f.label :role %><br />
        <ul class="list-unstyled">
          <li class="ml-5">
            <%= f.radio_button :admin, false %>
            <%= f.label(:admin, t(".admin")) %>
          </li>
          <li class="ml-5">
            <%= f.radio_button(:admin, true, checked: "checked") %>
            <%= f.label(:admin, t(".normal_user")) %>
          </li>
        </ul>
      </div>

      <div class="actions mt-2">
        <%= f.submit t(".update_user"), class: "btn btn-primary form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t(".all_user") %>
<%= link_to t(".create_new_user"),  new_admin_user_path, 
class: "btn btn-primary mb-1" %>

<table class="table table-bordered width_table">
  <tr class="background_tr">
    <th><%= t(".name") %></th>
    <th><%= t(".email") %></th> 
    <th><%= t(".address") %></th>
    <th><%= t(".phone") %></th>
    <th><%= t(".role") %></th>
    <th><%= t(".show") %></th>
    <th><%= t(".edit") %></th>
    <th><%= t(".delete") %></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.address %></td>
      <td><%= user.phone %></td>
      <td><%= user.role %></td>
      <td><%= link_to t(".show"), admin_user_path(user.id) %></td>
      <td><%= link_to t(".edit"), edit_admin_user_path(user.id) %></td>
      <td><%= link_to t(".delete"), admin_user_path(user.id),
        method: :delete,
        data: { confirm: t(".are_you_sure") } %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<h1 class="text-center"><%= t(".create_a_new_user") %></h1>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for [:admin, @user] do |f| %> 
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_field :address, class: "form-control" %>
      </div>
      
      <div class="field">
        <%= f.label :phone %><br />
        <%= f.text_field :phone, class: "form-control" %>
      </div>
      
      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, class: "form-control" %>
      </div> 

      <div class="field mt-3 border">
        <%= f.label :role %><br />
        <ul class="list-unstyled">
          <li class="ml-5">
            <%= f.radio_button :admin, false %>
            <%= f.label(:admin, t(".admin")) %>
          </li>
          <li class="ml-5">
            <%= f.radio_button(:admin, true, checked: "checked") %>
            <%= f.label(:admin, t(".normal_user")) %>
          </li>
        </ul>
      </div>

      <div class="actions mt-2">
        <%= f.submit t(".create_user"), class: "btn btn-primary form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <%= link_to t(".back_to_all_user"), admin_users_path, 
    class: "btn btn-primary mb-1" %>
  <div class="row">
    <div class="col">
      <table class="table table-bordered width_table">
        <tr class="background_tr">
          <th><%= t(".name") %></th>
          <th><%= t(".email") %></th>
          <th><%= t(".address") %></th>
          <th><%= t(".phone") %></th>
          <th><%= t(".role") %></th>
        </tr>
        
        <tr>
          <th><%= @user.name %></th>
          <th><%= @user.email %></th>
          <th><%= @user.address %></th>
          <th><%= @user.phone %></th>
          <th><%= @user.role %></th>
        </tr>
      </table>
    </div>
  </div>
</div>